# scaffold-class.ps1 - give every enabled class in courses.json the same agent setup.
# Creates sources\ work\ submissions\, AGENTS.md, CLAUDE.md, GEMINI.md, STATUS.md.
# Never overwrites STATUS.md or hand-written text in AGENTS.md: it refreshes only
# the block between the SHARED RULES markers. Rerun any time.
$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
# UTF-8 WITHOUT a BOM. PS 5.1's "-Encoding UTF8" writes a BOM, which breaks
# JSON.parse in Node and json.load in Python for any file another program reads,
# and leaves a stray glyph at the top of every markdown file.
function WriteUtf8($path, $text) {
  [System.IO.File]::WriteAllText($path, ([string]$text) + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
}

$cfg  = Get-Content (Join-Path $Root 'courses.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$tpl  = Get-Content (Join-Path $Root 'templates\shared-rules.md') -Raw -Encoding UTF8
$shared = $tpl -replace '\{\{OWNER\}\}', [string]$cfg.owner

# Only write shims for the agents the student actually uses. AGENTS.md is always
# written: it holds the rules themselves, and Codex reads it natively.
$agents = @($cfg.agents)
if (-not $agents) { $agents = @('claude', 'codex', 'antigravity') }
$shims = @{}
if ($agents -contains 'claude')      { $shims['CLAUDE.md'] = $true }
if ($agents -contains 'antigravity') { $shims['GEMINI.md'] = $true }

# Why materialise instead of "@../shared-rules.md"? Claude Code refuses to read
# a parent of the folder it was launched in, so a parent import silently loads
# nothing. Tested 2026-09-14. Copies between markers are refreshable and work
# for Claude Code, Codex and Antigravity alike.
$BEGIN = '<!-- BEGIN SHARED RULES - generated from templates\shared-rules.md by scaffold-class.ps1. Edit the template, not this block. -->'
$END   = '<!-- END SHARED RULES -->'
$sharedBlock = "$BEGIN`n`n$shared`n$END"
$stamp = Get-Date -Format 'yyyy-MM-dd'

foreach ($c in @($cfg.courses)) {
  if ($c.enabled -eq $false) { continue }
  $dir = Join-Path $Root $c.folder
  foreach ($sub in 'sources', 'work', 'submissions') { New-Item -ItemType Directory -Force -Path (Join-Path $dir $sub) | Out-Null }

  # This folder holds the student's name, grades and coursework. Write the
  # .gitignore BEFORE git init, so a repo never exists without it.
  $classIgnore = Join-Path $dir '.gitignore'
  if (-not (Test-Path $classIgnore)) {
    # AGENTS.md carries the owner's real name (substituted into the shared
    # rules), so it is excluded too. The agents read these off disk, not out of
    # git, so ignoring them costs nothing.
    WriteUtf8 $classIgnore @'
# Personal. This repo exists so Codex will open the folder, not to be published.
canvas/
sources/
work/
submissions/
STATUS.md
AGENTS.md
CLAUDE.md
GEMINI.md
'@
  }

  # Codex refuses any folder that is not a git repo ("Not inside a trusted
  # directory"), so without this it cannot open a single class folder.
  if ((Get-Command git -EA SilentlyContinue) -and -not (Test-Path (Join-Path $dir '.git'))) {
    git -C $dir init -q 2>&1 | Out-Null
  }

  $courseBlock = @"
## This course
| | |
|---|---|
| Canvas course id | $($c.id) |
| Canvas URL | $($cfg.base)/courses/$($c.id) |
| Canvas mirror | ``canvas/`` - regenerated every run, do not hand-edit |

## Course AI policy
**Not yet recorded.** Shared rule 8 applies until it is. Replace this section
once you have checked the syllabus or asked the instructor.
"@

  # Match on the stable marker PREFIX, not the full sentence. The comment text
  # inside the marker has changed between versions; an exact match would fail on
  # an older file and prepend a SECOND rules block, which then self-perpetuates.
  $blockRx = '(?s)<!-- BEGIN SHARED RULES.*?<!-- END SHARED RULES -->'
  $agentsPath = Join-Path $dir 'AGENTS.md'
  if (Test-Path $agentsPath) {
    $cur = Get-Content $agentsPath -Raw -Encoding UTF8
    if ($cur -match $blockRx) {
      # Replace EVERY block, so a file that already collected duplicates heals.
      WriteUtf8 $agentsPath ([regex]::Replace($cur, $blockRx, { $sharedBlock }))
      $msg = 'shared rules refreshed'
    } else {
      WriteUtf8 $agentsPath "$sharedBlock`n`n$cur"
      $msg = 'shared rules inserted; existing text kept'
    }
  } else {
    WriteUtf8 $agentsPath "# AGENTS.md - $($c.folder)`n`n$sharedBlock`n`n$courseBlock"
    $msg = 'created'
  }

  # A marker, not a size-and-contents guess: the old heuristic would delete a
  # shim the student had edited, as long as it stayed under 400 characters.
  $SHIM_MARK = '<!-- generated by scaffold-class.ps1 - delete this line to keep your edits -->'
  foreach ($shim in 'CLAUDE.md', 'GEMINI.md') {
    $p = Join-Path $dir $shim
    if ($shims.ContainsKey($shim)) {
      if (-not (Test-Path $p)) {
        WriteUtf8 $p "# $shim`n`n$SHIM_MARK`n`nThe rules for this folder live in AGENTS.md and are imported below.`nRead STATUS.md before working and update it after.`n`n@AGENTS.md`n@STATUS.md"
      }
    } elseif (Test-Path $p) {
      # Agent de-selected on a later run: remove the shim only if it is still
      # exactly what this script wrote. Anything else is the student's.
      if ((Get-Content $p -Raw -Encoding UTF8) -match [regex]::Escape($SHIM_MARK)) {
        Remove-Item $p -Force
      } else {
        Write-Host ("{0,-50} kept edited {1} (agent de-selected)" -f $c.folder, $shim)
      }
    }
  }

  $statusPath = Join-Path $dir 'STATUS.md'
  if (-not (Test-Path $statusPath)) {
    WriteUtf8 $statusPath @"
# STATUS - $($c.folder)

Last updated: $stamp (scaffolded)

Deadlines: ``canvas\assignments.md`` here, ``..\DUE.md`` for every class. Both
refresh on a schedule and can be hours behind. Confirm in Canvas (shared rule 6).

## Next step
Nothing recorded yet. Replace this line with the actual next action.

## Open questions
- What is this course's AI policy? Until answered, shared rule 8 applies.

## Log
- $stamp - Folder scaffolded.
"@
  }
  Write-Host ("{0,-50} {1}" -f $c.folder, $msg)
}
